framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'noreply@lycee-fulbert.fr'
        headers:
            from: 'Lyc√©e Fulbert <noreply@lycee-fulbert.fr>'
